"""Research-only Elliott vNext building blocks.

Module 6 remains outside productive scanner/trading logic until its separate
validation and integration gates are completed.
"""

from .pivots import (
    DEFAULT_PIVOT_SPECS,
    PivotSpec,
    aggregate_weekly,
    atr_series,
    detect_confirmed_pivots,
    detect_multidegree_pivots,
    prepare_daily_ohlcv,
)
from .scenarios import (
    CLASSIC_IMPULSE_RULES,
    CONSERVATIVE_SUPPORT,
    FULL_SUPPORT,
    ScenarioInputError,
    evaluate_correction_window,
    evaluate_motive_window,
    generate_scenario_sets,
)
from .fibonacci import (
    DEFAULT_ZONE_WIDTH_SPECS,
    W2_LEVELS,
    W3_LEVELS,
    W4_LEVELS,
    W5_RESEARCH_CANDIDATES,
    FibonacciInputError,
    ZoneWidthSpec,
    attach_fibonacci_geometry,
    build_wave2_retracement_map,
    wave2_depth_trigger,
)
from .routing import (
    ALLOWED_REVIEW_CONTEXTS,
    TRIGGER_POLICY,
    ExecutionCostSpec,
    RoutingInputError,
    attach_swing_routing,
    route_wave2_monitor,
)
from .cross_system import (
    ELLIOTT_REVIEW_ORIENTATION,
    MODEL_MATURITY,
    MODEL_STANCES,
    SCANNER_NUMERIC_ALIASES,
    TRANSITION_COLUMNS,
    CrossSystemConfig,
    CrossSystemInputError,
    build_event_windows,
    extract_elliott_events,
    join_model_claims,
    nearest_scanner_transitions,
    normalize_model_claims,
    scanner_feature_rows,
    summarize_cross_system,
)

__all__ = [
    "DEFAULT_PIVOT_SPECS",
    "PivotSpec",
    "aggregate_weekly",
    "atr_series",
    "detect_confirmed_pivots",
    "detect_multidegree_pivots",
    "prepare_daily_ohlcv",
    "CLASSIC_IMPULSE_RULES",
    "CONSERVATIVE_SUPPORT",
    "FULL_SUPPORT",
    "ScenarioInputError",
    "evaluate_correction_window",
    "evaluate_motive_window",
    "generate_scenario_sets",
    "DEFAULT_ZONE_WIDTH_SPECS",
    "W2_LEVELS",
    "W3_LEVELS",
    "W4_LEVELS",
    "W5_RESEARCH_CANDIDATES",
    "FibonacciInputError",
    "ZoneWidthSpec",
    "attach_fibonacci_geometry",
    "build_wave2_retracement_map",
    "wave2_depth_trigger",
    "ALLOWED_REVIEW_CONTEXTS",
    "TRIGGER_POLICY",
    "ExecutionCostSpec",
    "RoutingInputError",
    "attach_swing_routing",
    "route_wave2_monitor",
    "ELLIOTT_REVIEW_ORIENTATION",
    "MODEL_MATURITY",
    "MODEL_STANCES",
    "SCANNER_NUMERIC_ALIASES",
    "TRANSITION_COLUMNS",
    "CrossSystemConfig",
    "CrossSystemInputError",
    "build_event_windows",
    "extract_elliott_events",
    "join_model_claims",
    "nearest_scanner_transitions",
    "normalize_model_claims",
    "scanner_feature_rows",
    "summarize_cross_system",
]
