"""Pattern Discovery Lab v2 research-only bounded context.

L0 provides the hard research boundary. L1 adds deterministic pre-registration
and immutable Discovery Run manifests. L2 adds the versioned PIT-safe Feature
Library. L3 adds the bounded discovery-only Search Engine. L4 adds the
Statistical Discovery Guard. L5 adds the immutable Candidate Registry and
QM-C handoff. L6 adds the deterministic Dependency / Redundancy Graph. L7 adds
immutable prospective PIT claim capture. L8 adds immutable outcome maturation
after exact forward-session horizons. L9 adds governed prospective
confirmation/falsification. Later phases add rating and promotion.
"""

from .boundary import (
    BoundaryViolation,
    PatternDiscoveryBoundary,
    boundary_contract_hash,
    load_boundary_contract,
)
from .run_contract import (
    DiscoveryRunContractError,
    build_run_manifest,
    fingerprint_inputs,
    load_run_contract,
    manifest_repo_path,
    normalize_preregistration,
    run_contract_hash,
    verify_run_manifest,
    write_run_manifest,
)
from .feature_library import (
    FeatureLibrary,
    FeatureLibraryError,
    feature_library_hash,
    feature_version_hash,
    load_feature_library,
)
from .search_engine import (
    DiscoverySearchError,
    load_search_contract,
    run_discovery_search,
    search_contract_hash,
    search_result_repo_path,
    verify_search_result,
    write_search_result,
)
from .statistical_guard import (
    DiscoveryGuardError,
    apply_statistical_guard,
    evidence_repo_path,
    guard_contract_hash,
    load_guard_contract,
    verify_statistical_evidence,
    write_statistical_evidence,
)
from .candidate_registry import (
    CandidateFreezeError,
    PatternCandidateRegistry,
    build_frozen_pattern_record,
    candidate_registry_contract_hash,
    freeze_candidates,
    freeze_snapshot_repo_path,
    load_candidate_registry_contract,
    pattern_id_for_candidate,
    validate_applied_qm_handoff,
    verify_freeze_snapshot,
    write_freeze_snapshot,
)
from .dependency_graph import (
    DependencyGraphError,
    build_dependency_graph,
    build_event_context,
    dependency_graph_contract_hash,
    dependency_graph_repo_path,
    load_dependency_graph_contract,
    verify_dependency_graph,
    verify_event_context,
    write_dependency_graph,
)
from .prospective_capture import (
    ProspectiveCaptureError,
    ProspectiveClaimRegistry,
    build_prospective_capture,
    capture_report_repo_path,
    load_prospective_capture_contract,
    match_frozen_pattern,
    persist_prospective_capture,
    prospective_capture_contract_hash,
    prospective_claim_registry_repo_path,
    verify_capture_report,
    verify_prospective_claim,
)
from .outcome_maturation import (
    MaturedOutcomeRegistry,
    OutcomeMaturationError,
    build_outcome_maturation_check,
    evaluate_claim_maturation,
    load_outcome_maturation_contract,
    maturation_check_repo_path,
    maturation_registry_repo_path,
    outcome_maturation_contract_hash,
    persist_outcome_maturation,
    verify_maturation_check,
    verify_matured_outcome,
)
from .confirmation_engine import (
    ConfirmationEngineError,
    ConfirmationLookRegistry,
    baseline_bundle_repo_path,
    build_baseline_bundle,
    build_confirmation_look,
    build_context_bundle,
    confirmation_contract_hash,
    confirmation_registry_repo_path,
    confirmation_report_repo_path,
    context_bundle_repo_path,
    load_confirmation_contract,
    persist_confirmation_look,
    validate_applied_qm_confirmation_handoff,
    verify_baseline_bundle,
    verify_confirmation_look,
    verify_context_bundle,
)

__all__ = [
    "BoundaryViolation",
    "PatternDiscoveryBoundary",
    "boundary_contract_hash",
    "load_boundary_contract",
    "DiscoveryRunContractError",
    "build_run_manifest",
    "fingerprint_inputs",
    "load_run_contract",
    "manifest_repo_path",
    "normalize_preregistration",
    "run_contract_hash",
    "verify_run_manifest",
    "write_run_manifest",
    "FeatureLibrary",
    "FeatureLibraryError",
    "feature_library_hash",
    "feature_version_hash",
    "load_feature_library",
    "DiscoverySearchError",
    "load_search_contract",
    "run_discovery_search",
    "search_contract_hash",
    "search_result_repo_path",
    "verify_search_result",
    "write_search_result",
    "DiscoveryGuardError",
    "apply_statistical_guard",
    "evidence_repo_path",
    "guard_contract_hash",
    "load_guard_contract",
    "verify_statistical_evidence",
    "write_statistical_evidence",
    "CandidateFreezeError",
    "PatternCandidateRegistry",
    "build_frozen_pattern_record",
    "candidate_registry_contract_hash",
    "freeze_candidates",
    "freeze_snapshot_repo_path",
    "load_candidate_registry_contract",
    "pattern_id_for_candidate",
    "validate_applied_qm_handoff",
    "verify_freeze_snapshot",
    "write_freeze_snapshot",
    "DependencyGraphError",
    "build_dependency_graph",
    "build_event_context",
    "dependency_graph_contract_hash",
    "dependency_graph_repo_path",
    "load_dependency_graph_contract",
    "verify_dependency_graph",
    "verify_event_context",
    "write_dependency_graph",
    "ProspectiveCaptureError",
    "ProspectiveClaimRegistry",
    "build_prospective_capture",
    "capture_report_repo_path",
    "load_prospective_capture_contract",
    "match_frozen_pattern",
    "persist_prospective_capture",
    "prospective_capture_contract_hash",
    "prospective_claim_registry_repo_path",
    "verify_capture_report",
    "verify_prospective_claim",
    "MaturedOutcomeRegistry",
    "OutcomeMaturationError",
    "build_outcome_maturation_check",
    "evaluate_claim_maturation",
    "load_outcome_maturation_contract",
    "maturation_check_repo_path",
    "maturation_registry_repo_path",
    "outcome_maturation_contract_hash",
    "persist_outcome_maturation",
    "verify_maturation_check",
    "verify_matured_outcome",
    "ConfirmationEngineError",
    "ConfirmationLookRegistry",
    "baseline_bundle_repo_path",
    "build_baseline_bundle",
    "build_confirmation_look",
    "build_context_bundle",
    "confirmation_contract_hash",
    "confirmation_registry_repo_path",
    "confirmation_report_repo_path",
    "context_bundle_repo_path",
    "load_confirmation_contract",
    "persist_confirmation_look",
    "validate_applied_qm_confirmation_handoff",
    "verify_baseline_bundle",
    "verify_confirmation_look",
    "verify_context_bundle",
]
